### ISSUE TITLE
[Feature Request] Use Built-In Conversion Rates for Currency

### ISSUE THREAD

**Issue by InfraredAces** [DeVelox/lazymoney#1]
Currently, Lazy Money has it's own internal conversion rates between the 5 units of currency. Foundry 5E, in its latest update, now has the conversion rates set in the module/config.js file

**Comment by DeVelox** [comment]
I looked into it but that particular format seems useful for converting everything into plat but in my use case of converting arbitrary denominations it only seems to make things more complicated with no added benefit.
I also find it highly unlikely WotC will change the currency rates during 5e's lifetime so not relying on DND5E's API for this should be fine.

**Comment by InfraredAces** [comment]
My request is because I have a module that allows users to alter those currency rates to custom rates. So by using that DND5E's API, people are able to set their own rates between the different currencies and still get all the benefits of Lazy Money.

**Comment by DeVelox** [comment]
I changed it so that my cpValue object is now generated from the DND5E config.
