### ISSUE TITLE
Currency seems to be resetting

### ISSUE THREAD

**Issue by samgrieve** [DeVelox/lazymoney#11]
PC currently has 5GP and nothing else. If I type -2CP and hit enter the gold becomes 0 and Copper -2.

Adding currency appears to work fine but subtracting causes issues.

**Comment by samgrieve** [comment]
Some further tests show the issue appears to be anytime conversion is required. Adding or subtracting copper which doesn't go above or below 10 is fine.

If CP is at 4 and I add +7 I get 1CP and no silver gained.

**Comment by DeVelox** [comment]
Fixed.
