### ISSUE TITLE
[FEATURE REQUEST] Currency change logging

### ISSUE THREAD

**Issue by benbarbour** [DeVelox/lazymoney#12]
May players love this module, but also sometimes typo terribly and/or forget to enter the "+" symbol. It would be _great_ to have an optional feature that would output currency changes to the chat log (maybe whisper to GM only?) so that I can easily undo such mistakes.

Maybe you don't think this module is the right place for this. If so, feel free to close it.

**Comment by DeVelox** [comment]
I've implemented it in a fairly basic way, hopefully this is to your liking. It shows the changes that the players attempted to make, not post-conversion, personally I thought it might be more useful to know what they tried typing in.
![image](https://user-images.githubusercontent.com/1922928/147577756-1dc8cc45-1e1c-4d90-a2f5-24720cc00ae0.png)

**Comment by benbarbour** [comment]
That's great, thank you very much!
