### ISSUE TITLE
Lazy Money does not work with Loot Sheet NPC 5e

### ISSUE THREAD

**Issue by DawidIzydor** [DeVelox/lazymoney#13]
The Lazy Money module functionality does not work with the Loot Sheet NPC 5e module's sheet. When trying to subtract any money from the money bar in an actor configured with "dnd5e.LootSheetNPC5e" sheet, instead of decreasing the money it's overriden.

Steps to reproduce
1. Create an NPC actor in Foundry VTT
2. Change it's sheet to "dnd5e.LootSheetNPC5e"
3. Change owned money to any amount (eg 100 gp)
4. Subtract any amount of money (eg -1 gp) - instead of showing 99 gp the bar shows -1 gp

![image](https://user-images.githubusercontent.com/30767613/147653116-1e772240-5f05-443a-b4a2-1705d4c9ef0a.png)
![image](https://user-images.githubusercontent.com/30767613/147653131-84c250b3-7f41-434a-a53e-758ef5e43b74.png)
![image](https://user-images.githubusercontent.com/30767613/147653140-1bfaf215-9c66-47b1-a628-67dda7c923a9.png)

Actors with standard sheet work correctly with both module installed

**Comment by DawidIzydor** [comment]
Created PR with changes for this compability, tested on Foundry V9 build 238, works correctly https://github.com/DeVelox/lazymoney/pull/14

**Comment by DeVelox** [comment]
Thank you, I have merged your PR.
