### ISSUE TITLE
Conversion not working 

### ISSUE THREAD

**Issue by d1ScreT** [DeVelox/lazymoney#4]
Hello DeVlox,

I like to use your module for our session since it is very handy. The current problem is that the conversion is not working properly in Foundry VTT version **0.7.9** with DnD5e version **1.2.4**. Maybe they've change some names of the currencies. Could you take a look at it. 

### Thanks !

Some infos that might be helpful:

---
![06-03-_2021_11-04-34](https://user-images.githubusercontent.com/80152516/110202956-e5fb8a80-7e6b-11eb-884a-e64e0d33bfa6.gif)
---
![image](https://user-images.githubusercontent.com/80152516/110203041-31159d80-7e6c-11eb-8fa1-f870e1fce214.png)

---

**Comment by DeVelox** [comment]
I just tried it in my test environment with FVTT 0.7.9, DnD5e 1.2.4 and no other modules enabled and it seems to be working fine.
Try pressing F12, going to the Network tab, ticking Disable Cache and refreshing the page with the F12 panel still open.
If that doesn't work, check the console tab for any errors when you edit the currencies.

**Comment by d1ScreT** [comment]
Classic layer 8 error. It`s working now. Forgot to activate the module in the "Manage Modules" settings. Funny thing is that the "money bar" is now where it was before installing the module. 

before installing
![image](https://user-images.githubusercontent.com/80152516/110213945-908ea000-7ea2-11eb-92c8-3a8117a34fbd.png)

after installing
![image](https://user-images.githubusercontent.com/80152516/110213956-a56b3380-7ea2-11eb-9db9-98240d13a2bc.png)

after reloading now with activated module
![image](https://user-images.githubusercontent.com/80152516/110213977-bb78f400-7ea2-11eb-83c4-8d757bec77a3.png)


I thought it was acitvated since something changed the "money bar".

Sorry for taking your time. 

Have a nice day!
