### ISSUE TITLE
Issues with calculating down with 1 coin type between

### ISSUE THREAD

**Issue by Nordiii** [DeVelox/lazymoney#7]
Thanks for your fast responses and help, sadly I found another problem.

In case you pay 1GP but you only have 100CP it does not work.

### Example 1:
0GP 0SP 100CP | GP "0-1"

**Expected:**
0GP 0SP 0CP

**Actual:**
blank GP 0SP 100CP

**Error:**
```
Uncaught TypeError: Cannot read property 'value' of undefined
    at removeMoney (lazymoney.js:192)
    at HTMLInputElement._onChangeCurrency (lazymoney.js:71)
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.v.handle (jquery.min.js:2)
```
### Example 2:
0GP 0SP 100CP | GP "-1"

**Expected:**
0GP 0SP 0CP

**Actual:**
-1GP 0SP 100CP

**Error:** 
none

**Comment by DeVelox** [comment]
This is a an issue that seems to appear only when dealing with an exact amount of copper that would leave the total at 0. If there is any currency left over (e.g. 101cp) or if you try the same with plat and silver, it works properly. That's assuming you have the latest change I pushed some 30 minutes after the 0.9.12 version as I really didn't want to spam the Foundry module repository.

I will have to look into this specific case tomorrow.

**Comment by Nordiii** [comment]
I will re check tomorrow too. Could swear it was not only for this case.

**Comment by DeVelox** [comment]
Pushed another update just now. This one seems to be working even with the 100cp -1gp example.
