### ISSUE TITLE
[Feature Request] Allow custom exchange rates

### ISSUE THREAD

**Issue by tagnullde** [DeVelox/lazymoney#9]
Hey,

I would love a feature that allows me to edit the exchange rates. Like

- 100 Copper = 1 Silver (like an free form input field)
- 100 Silver = 1 Gold
- Ignore nominations like Electrum (checkboxes so I can pick and choose what my campaign has)

Thank your for your time and effort.

**Comment by DeVelox** [comment]
This is already possible to do with other modules as the exchange rate is taken from `CONFIG.DND5E.currencyConversion`

You should be able to use this module for changing the exchange rates: https://foundryvtt.com/packages/5e-custom-currency
Lazy Money might not be compatible with some of the more advanced options that module offers, though.

Ignoring Electrum is already an option and I decided to keep it at that as I feel the rest are perfectly reasonable in any fantasy setting.

**Comment by tagnullde** [comment]
Oh - I haven't seen that module. Thanks for pointing it out to me. :)
Have a nice one.
